// Desktop app, part 2: scenes, capture, observer mode, outputs, data correction, offline sync.
import { C, TONES, AMBER, img, screen, desktopShell, ann, chip, tally, health, monitor, icon, crestMini, sectionTitle, mark } from '../hud-kit.mjs';

const wrap = (id, active, body, anns, opts = {}) => screen({ id, body: desktopShell({ active, body, ...opts }) + anns });

export function scenes() {
  const tree = [
    ['Holding', 'Holding', [['Esportra · Holding', 'browser', 'ok'], ['Esportra · Ticker', 'browser', 'ok']]],
    ['Gameplay', 'Map · live rounds', [['Game feed', 'slot', 'warn'], ['Esportra · In-game HUD', 'browser', 'ok']]],
    ['Fullscreen', 'Intro, veto, agent select, results', [['Esportra · Fullscreen scenes', 'browser', 'ok'], ['Background loop', 'media', 'ok']]],
    ['Replay', 'Replays', [['Replay buffer playback', 'media', 'ok'], ['Esportra · Replay bug', 'browser', 'ok']]],
    ['Casters', 'Desk segments', [['Caster cam 1', 'slot', 'warn'], ['Caster cam 2', 'slot', 'warn'], ['Esportra · Casters', 'browser', 'ok']]],
  ];
  const srcRow = ([n, kind, st]) => `<div class="row" style="gap:10px;height:32px;padding:0 12px 0 34px;font-size:12.5px;${kind === 'slot' ? `color:${C.secondary}` : ''}">${icon(kind === 'browser' ? 'link' : kind === 'media' ? 'play' : 'plus', kind === 'slot' ? C.warning : C.hint, 12)}${n}${kind === 'slot' ? `<span class="chip" style="margin-left:auto;color:#FDE68A;box-shadow:inset 0 0 0 1px rgba(251,191,36,.4)">Add your source</span>` : `<span class="mono hint" style="margin-left:auto;font-size:10.5px">${kind === 'browser' ? '1920×1080' : 'media'}</span>`}</div>`;
  const body = `<div style="position:absolute;inset:0;padding:22px 24px;display:grid;grid-template-columns:330px 1fr 420px;gap:18px">
<div style="display:flex;flex-direction:column;gap:14px">
<div class="box" style="padding:16px">${sectionTitle('CONNECTION', chip('Connected', 'success'))}
<div class="row" style="gap:12px">${icon('scenes', C.ink, 22)}<div><b style="font-size:14px">OBS Studio 30.2</b><div class="hint" style="font-size:12px">This PC · ws://localhost:4455</div></div></div>
<div class="sep" style="margin:14px 0"></div>
${[['Studio Mode', 'On · takes go through Preview', true], ['Scene collection', 'Esportra · KVO Playoffs', null], ['Control', 'Scenes, transitions, replay buffer', null]].map(([k, v, t]) => `<div class="row" style="gap:10px;padding:6px 0"><div style="min-width:0"><div style="font-size:12.5px;font-weight:600">${k}</div><div class="hint" style="font-size:11.5px">${v}</div></div>${t !== null ? `<span class="tog on" style="margin-left:auto"></span>` : ''}</div>`).join('')}</div>
<div class="box" style="padding:16px">${sectionTitle('MORE SWITCHERS')}
<div class="row" style="gap:10px;padding:8px 0">${icon('scenes', C.secondary, 16)}<div><b style="font-size:13px">vMix · Booth B</b><div class="hint" style="font-size:11.5px">HTTP API · 192.168.1.52:8088</div></div><span style="margin-left:auto">${chip('Linked', 'success')}</span></div>
<span class="b b-sm" style="margin-top:8px">${icon('plus', C.ink, 12)} Add OBS or vMix</span></div>
<div class="box2" style="padding:14px"><div class="cap" style="font-size:9px">HOW IT TALKS TO OBS</div><p class="muted" style="font-size:12.5px;margin-top:8px;line-height:1.55">OBS’s built-in WebSocket server (Tools → WebSocket Server Settings). The app switches scenes, picks transitions and saves replays. Graphics inside each scene update on their own.</p></div></div>
<div class="box" style="padding:0;display:flex;flex-direction:column">
<div class="row" style="justify-content:space-between;padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.06)"><div><div class="cap">SCENES IN OBS · BUILT BY ESPORTRA</div><p class="hint" style="font-size:12px;margin-top:6px">Created in one click. Three slots wait for your own sources.</p></div><span class="b b-sm">Rebuild</span></div>
<div>${tree.map(([scene, used, srcs], i) => `<div style="border-bottom:1px solid rgba(255,255,255,.05)"><div class="row" style="gap:10px;height:40px;padding:0 12px;${i === 1 ? `background:rgba(244,63,94,.07);box-shadow:inset 2px 0 0 ${C.cue}` : ''}">${icon('scenes', C.secondary, 14)}<b style="font-size:13.5px">${scene}</b><span class="hint" style="font-size:11.5px">${used}</span><span style="margin-left:auto">${i === 1 ? tally('pgm') : i === 3 ? tally('pvw') : ''}</span></div>${srcs.map(srcRow).join('')}</div>`).join('')}</div>
<div style="flex:1;padding:16px 18px;display:flex;gap:16px;border-top:1px solid rgba(255,255,255,.06)">${monitor(img('ingame-cams.jpg'), { w: 300, label: 'GAMEPLAY · COMPOSED', tone: 'idle' })}
<div style="min-width:0"><div class="cap" style="font-size:9px">LAYER ORDER</div>${[['1', 'Esportra · In-game HUD', 'Transparent, on top'], ['2', 'Game feed', 'Your NDI or game capture'], ['3', 'Background', 'Only if the feed drops']].map(([n, t, d]) => `<div class="row" style="gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05)"><span class="mono hint" style="font-size:11px">${n}</span><div><span style="font-size:12.5px">${t}</span><div class="hint" style="font-size:11px">${d}</div></div></div>`).join('')}</div></div>
<div class="row" style="gap:10px;padding:14px 18px;border-top:1px solid rgba(255,255,255,.06);background:rgba(251,191,36,.05)">${icon('alert', C.warning, 14)}<span style="font-size:12.5px">3 slots need your sources: game feed, caster cam 1 and 2. Add them in OBS; we detect them.</span></div></div>
<div style="display:flex;flex-direction:column;gap:14px">
<div class="box" style="padding:16px">${sectionTitle('SEGMENT → SCENE')}
<table class="tbl"><tr><th>Segment</th><th>Scene</th><th>Transition</th></tr>${[['Starting soon', 'Holding', 'Fade 500'], ['Match intro', 'Fullscreen', 'Stinger'], ['Map veto', 'Fullscreen', 'Cut'], ['Live rounds', 'Gameplay', 'Stinger'], ['Replay', 'Replay', 'Stinger'], ['Map result', 'Fullscreen', 'Stinger'], ['Casters desk', 'Casters', 'Fade 500']].map(([a, b, t]) => `<tr><td style="padding:8px 10px">${a}</td><td style="padding:8px 10px"><span class="field" style="height:28px;font-size:12.5px;display:inline-flex;gap:8px">${b} ${icon('chevron', C.hint, 11)}</span></td><td class="mono hint" style="padding:8px 10px;font-size:11px">${t}</td></tr>`).join('')}</table></div>
<div class="box" style="padding:16px">${sectionTitle('TRANSITIONS & REPLAYS')}
<div style="display:grid;gap:12px"><div><div class="lbl">Stinger</div><div class="field row" style="gap:8px">${icon('play', C.secondary, 12)} esportra-stinger.webm <span class="hint" style="margin-left:auto">cut at 600 ms</span></div></div>
<div><div class="lbl">Replay buffer</div><div class="row" style="gap:10px"><div class="field" style="flex:1">Last 20 s · saved on replay key</div><span class="tog on"></span></div></div>
<div class="row" style="gap:10px"><span class="b b-sm b-cue">${icon('play', '#FDE68A', 11)} Test the stinger</span><span class="b b-sm">Test replay</span></div></div></div></div></div>`;
  return wrap('hud/desk-09-scenes', 'Scenes', body, `${ann(1, 85, 93)}${ann(2, 434, 93)}${ann(3, 434, 735)}${ann(4, 1145, 93)}${ann(5, 1145, 516)}`);
}

export function capture() {
  const feat = [['match_info', 'Map, mode, round, score', 'live', '0.4 s'], ['roster', 'Players, agents, teams', 'live', '1 min'], ['scoreboard', 'Credits, guns, armor, ult, K/D/A', 'live', '0.2 s'], ['kill', 'Killfeed, headshots, weapons', 'live', '3 s'], ['round_phase', 'Buy, live, end', 'live', '0.8 s'], ['spike', 'Planted, defused', 'derived', 'From plant event'], ['health', 'Other players’ HP', 'derived', 'Player PCs only'], ['round_timer', 'Time left', 'derived', 'Counted locally']];
  const st = (s) => (s === 'live' ? chip('Live', 'success') : chip('Covered', 'warning'));
  const body = `<div style="position:absolute;inset:0;padding:22px 24px;display:grid;grid-template-columns:1fr 440px;gap:18px">
<div style="display:flex;flex-direction:column;gap:14px">
<div class="grid-px" style="grid-template-columns:repeat(4,1fr);box-shadow:0 0 0 1px rgba(255,255,255,.06)">${[['SOURCE', 'Observer PC 1', 'Capture-only app · LAN'], ['LATENCY', '38 ms', 'Median, last 5 min'], ['MESSAGES', '46 / s', 'GEP events in'], ['GAPS', '0', 'Resyncs this map']].map(([l, v, s2]) => `<div style="padding:14px 16px"><div class="cap" style="font-size:9px">${l}</div><div class="t1" style="font-size:22px;margin-top:8px">${v}</div><div class="hint" style="font-size:11.5px;margin-top:3px">${s2}</div></div>`).join('')}</div>
<div class="box" style="padding:14px 16px">${sectionTitle('GEP FEATURES · VALORANT', '<span class="hint" style="font-size:12px">What the game sends, and how we fill the gaps</span>')}
<table class="tbl"><tr><th>Feature</th><th>Gives the HUD</th><th>Status</th><th>Fresh</th><th style="width:140px">Last 60 s</th></tr>${feat.map(([f, d, s2, fr], i) => `<tr><td class="mono" style="font-size:12px">${f}</td><td class="muted" style="font-size:12.5px">${d}</td><td>${st(s2)}</td><td class="mono hint" style="font-size:11px">${fr}</td><td><div class="row" style="gap:2px;height:14px;align-items:flex-end">${Array.from({ length: 20 }, (_, k) => `<span style="flex:1;height:${s2 === 'live' ? 4 + ((k * 7 + i * 3) % 10) : 3}px;background:${s2 === 'live' ? 'rgba(52,211,153,.7)' : 'rgba(251,191,36,.45)'}"></span>`).join('')}</div></td></tr>`).join('')}</table></div>
<div class="box" style="padding:14px 16px">${sectionTitle('PLAYER PCS · OPTIONAL', '<span class="b b-sm">Send setup link</span>')}
<p class="muted" style="font-size:12.5px">Install the capture app on player PCs to add exact health and ability charges. Without them, the HUD uses what the observer sees.</p>
<div class="row" style="gap:6px;margin-top:12px">${['JUNO', 'MIRA', 'DAX', 'RIKU', 'ECHO', 'KAIRO', 'SOL', 'VEX', 'NYX', 'ZEN'].map((p, i) => `<span class="chip" style="${i < 3 ? 'color:#6EE7B7;box-shadow:inset 0 0 0 1px rgba(52,211,153,.4)' : `color:${C.hint};box-shadow:inset 0 0 0 1px rgba(255,255,255,.1)`}">${p}</span>`).join('')}</div></div></div>
<div style="display:flex;flex-direction:column;gap:14px">
<div class="box" style="padding:14px 16px">${sectionTitle('LIVE STATE', chip('v 18,204', 'neutral'))}
<div class="mono" style="font-size:11.5px;line-height:1.8;color:${C.label};background:#08080a;padding:12px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.06)">round: <span style="color:#FDE68A">24</span> · phase: <span style="color:#FDE68A">"live"</span><br>score: [<span style="color:#FDE68A">11</span>, <span style="color:#FDE68A">12</span>] · spike: <span style="color:#FDE68A">"B"</span><br>observed: <span style="color:#FDE68A">"KAIRO"</span> · hp 100 · armor 50<br>alive: [3, 2] · bank: [8700, 13100]<br>killfeed[0]: KAIRO ▸ VEX · vandal · hs</div></div>
<div class="box" style="padding:14px 16px">${sectionTitle('SIMULATE · NO GAME NEEDED')}
<div class="seg" style="margin-bottom:12px"><span class="on">Recorded match</span><span>Scripted round</span></div>
<div class="field row" style="gap:8px">${icon('data', C.secondary, 13)} kvo-ub-semi-map2.ndjson <span class="hint" style="margin-left:auto">41 min</span></div>
<div style="position:relative;height:30px;margin-top:14px"><div class="bar" style="position:absolute;left:0;right:0;top:13px"><i style="width:38%"></i></div><span style="position:absolute;left:38%;top:6px;width:4px;height:18px;background:${C.ink}"></span>${[12, 24, 51, 63, 77].map((x) => `<span style="position:absolute;left:${x}%;top:22px;width:2px;height:8px;background:${C.hint}"></span>`).join('')}</div>
<div class="row" style="gap:8px;margin-top:8px"><span class="b b-sm">${icon('play', C.ink, 11)} Play</span><span class="b b-sm">1×</span><span class="mono hint" style="margin-left:auto;font-size:11px">R9 · 15:42</span></div>
<p class="hint" style="font-size:12px;margin-top:10px">Drives every graphic and the autopilot as if it were live. OBS is not switched unless you allow it.</p></div>
<div class="box" style="padding:14px 16px">${sectionTitle('FALLBACK RULES · FIELDS GEP DOESN’T SEND')}${[['Spike timer', '45 s from the plant event; defuse markers at 7 s and 3.5 s'], ['Round timer', 'Counted from the phase change, corrected when GEP sends time'], ['Other players’ health', 'Hidden unless their PC runs the capture app']].map(([t, d]) => `<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05)"><b style="font-size:12.5px">${t}</b><div class="hint" style="font-size:11.5px;margin-top:2px">${d}</div></div>`).join('')}</div></div></div>`;
  return wrap('hud/desk-10-capture', 'Capture', body, `${ann(1, 85, 93)}${ann(2, 85, 201)}${ann(3, 85, 667)}${ann(4, 1125, 93)}${ann(5, 1125, 296)}${ann(6, 1125, 590)}`);
}

export function observer() {
  // Compact window on the observer PC: capture only, no controls.
  const body = `<div style="position:absolute;inset:0;background:radial-gradient(ellipse at 30% 20%,#1a1a20,#08080a)">
<div style="position:absolute;inset:0;background:url('${img('agent-select.jpg')}') center/cover;opacity:.18;filter:blur(2px)"></div>
<div class="box" style="position:absolute;left:50%;top:50%;width:620px;margin-left:-310px;margin-top:-260px;background:#0b0b0d;box-shadow:0 30px 80px rgba(0,0,0,.6),inset 0 0 0 1px rgba(255,255,255,.1)">
<div class="row" style="height:34px;padding:0 12px;gap:10px;border-bottom:1px solid rgba(255,255,255,.06)">${mark(13)}<span class="cap" style="font-size:9px;color:${C.secondary}">ESPORTRA BROADCAST · CAPTURE ONLY</span><span class="row" style="margin-left:auto;gap:12px;color:${C.hint}"><span style="width:10px;height:1px;background:currentColor"></span>${icon('x', C.hint, 11)}</span></div>
<div style="padding:24px 26px">
<div class="row" style="gap:14px"><span style="width:12px;height:12px;background:${C.success};box-shadow:0 0 0 5px rgba(52,211,153,.15)"></span><div><h2 class="t1" style="font-size:24px">Sending game data</h2><p class="muted" style="font-size:13px;margin-top:4px">to <b style="color:${C.ink}">Studio PC</b> · 192.168.1.40 · 38 ms</p></div></div>
<div class="grid-px" style="grid-template-columns:repeat(3,1fr);margin-top:20px;box-shadow:0 0 0 1px rgba(255,255,255,.06)">${[['VALORANT', 'Observer client'], ['GEP', '11 / 11 features'], ['SENT', '46 msgs / s']].map(([a, b]) => `<div style="padding:12px 14px"><div class="cap" style="font-size:9px">${a}</div><div style="font-size:13.5px;font-weight:600;margin-top:6px">${b}</div></div>`).join('')}</div>
<div style="margin-top:18px">${sectionTitle('HOTKEYS ON THIS PC')}${[['Mark replay', 'F9'], ['Flag a moment for the producer', 'F10'], ['Pause sending', 'Ctrl Shift P']].map(([t, k]) => `<div class="row" style="justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.05);font-size:13px"><span>${t}</span><span class="kbd">${k}</span></div>`).join('')}</div>
<div class="row" style="gap:10px;margin-top:20px"><span class="b">Pause sending</span><span class="b">Change production PC</span><span class="hint" style="font-size:11.5px;margin-left:auto">No show controls here</span></div></div></div>
<div class="box2" style="position:absolute;right:28px;bottom:28px;width:300px;padding:14px"><div class="cap" style="font-size:9px">WHY A SEPARATE MODE</div><p class="muted" style="font-size:12px;margin-top:6px;line-height:1.5">GEP only runs next to the game. The observer PC sends data and nothing else, so a stray click there can never change what’s on air.</p></div></div>`;
  return screen({ id: 'hud/desk-11-observer', body: `<div class="row" style="height:34px;padding:0 14px;background:#060607;gap:10px"><span class="cap" style="font-size:9px">OBSERVER PC 1 · WINDOWS DESKTOP</span></div><div style="position:relative;height:calc(100% - 34px)">${body}</div>${ann(1, 476, 300)}${ann(2, 476, 392)}${ann(3, 476, 480)}${ann(4, 476, 660)}` });
}

export function outputs() {
  const out = [['In-game HUD', 'ingame.jpg', 'ingame', 2, 'pgm'], ['Fullscreen scenes', 'map-result.jpg', 'fullscreen', 1, 'pvw'], ['Holding', 'starting-soon.jpg', 'holding', 1, 'off'], ['Replay bug', 'replay.jpg', 'replay', 1, 'off'], ['Casters', 'casters.jpg', 'casters', 0, 'off'], ['Stinger (live)', 'stinger-mid.jpg', 'stinger', 1, 'off']];
  const card = ([n, f, path, clients, t]) => `<div class="box" style="padding:12px">${monitor(img(f), { w: 330, label: t === 'pgm' ? 'ON AIR' : t === 'pvw' ? 'PVW' : 'READY', tone: t === 'pgm' ? 'pgm' : t === 'pvw' ? 'pvw' : 'idle' })}
<div class="row" style="justify-content:space-between;margin-top:10px"><b style="font-size:13.5px">${n}</b>${clients ? chip(`${clients} connected`, 'success') : chip('Not in OBS', 'critical')}</div>
<div class="row" style="gap:6px;margin-top:8px"><div class="field mono" style="flex:1;height:30px;font-size:11px;color:${C.secondary}">…:5300/o/${path}?k=••••</div><span class="b b-sm" style="width:30px;padding:0">${icon('copy', C.ink, 12)}</span></div>
<div class="row" style="gap:12px;margin-top:8px" class="mono"><span class="mono hint" style="font-size:10.5px">1920×1080 · 60 fps</span><span class="mono hint" style="font-size:10.5px;margin-left:auto">last frame 0.1 s</span></div></div>`;
  const body = `<div style="position:absolute;inset:0;padding:22px 24px">
<div class="row" style="justify-content:space-between;margin-bottom:16px"><div><div class="cap">OUTPUTS · BROWSER SOURCES SERVED BY THIS PC</div><p class="hint" style="font-size:12.5px;margin-top:6px">Add each once in OBS. They never need to change: the content follows the show.</p></div>
<div class="row" style="gap:10px"><span class="seg"><span>This PC</span><span class="on">LAN</span><span>Cloud relay</span></span><span class="b b-sm">Test pattern on all</span></div></div>
<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px">${out.slice(0, 4).map(card).join('')}${out.slice(4).map(card).join('')}
<div class="box2" style="grid-column:span 2;padding:16px"><div class="cap" style="font-size:9px">CONNECTED MEANS</div><p class="muted" style="font-size:12.5px;margin-top:8px;line-height:1.55">The page is open in OBS or vMix and talking to this PC. Two connections on In-game HUD usually mean the source sits in two scenes, which is fine.</p>
<div class="row" style="gap:10px;margin-top:12px">${icon('qr', C.secondary, 16)}<span class="hint" style="font-size:12px">Scan to open any output on a phone or a second screen for checks.</span></div></div></div>
<div class="box" style="margin-top:14px;padding:14px 16px">${sectionTitle('ADDING ONE BY HAND · IF YOU SKIPPED THE ONE-CLICK BUILD')}
<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px">${[['1', 'OBS → Sources → + → Browser'], ['2', 'Paste the URL · 1920 × 1080'], ['3', 'Leave “Shutdown source when not visible” off'], ['4', 'It turns green here within a second']].map(([n, t]) => `<div class="row" style="gap:10px;padding:12px;background:rgba(255,255,255,.03);box-shadow:inset 0 0 0 1px rgba(255,255,255,.06)"><span class="mono" style="width:22px;height:22px;display:flex;align-items:center;justify-content:center;box-shadow:inset 0 0 0 1px rgba(255,255,255,.25);font-size:11px">${n}</span><span style="font-size:12.5px">${t}</span></div>`).join('')}</div></div></div>`;
  return wrap('hud/desk-12-outputs', 'Outputs', body, `${ann(1, 74, 128)}${ann(2, 1160, 112)}${ann(3, 85, 400)}${ann(4, 85, 790)}`);
}

export function dataFix() {
  const body = `<div style="position:absolute;inset:0;background:url('${img('ingame-full.jpg')}') center/cover;opacity:.12"></div>
<div style="position:absolute;inset:0;background:linear-gradient(90deg,rgba(9,9,11,.92),rgba(9,9,11,.75))"></div>
<div style="position:absolute;right:0;top:0;bottom:0;width:560px;background:#0b0b0d;box-shadow:-24px 0 60px rgba(0,0,0,.5),inset 1px 0 0 rgba(255,255,255,.08);padding:22px 24px;overflow:hidden">
<div class="row" style="justify-content:space-between"><div><div class="cap">FIX DATA · LIVE</div><h2 class="t1" style="font-size:24px;margin-top:10px">Correct what’s on screen</h2></div>${icon('x', C.hint, 16)}</div>
<p class="muted" style="font-size:12.5px;margin-top:8px">Changes go on air as soon as you apply them. The feed won’t overwrite a field you fixed until the next round.</p>
<div style="margin-top:18px">${sectionTitle('SCORE')}<div class="row" style="gap:12px">${['Night Owls', 'Crimson Five'].map((t, i) => `<div style="flex:1;padding:12px;background:rgba(255,255,255,.03);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)"><div class="row" style="gap:8px">${crestMini(i ? 'C5' : 'NO', i ? 0 : 265, 18, i ? 2 : 0)}<b style="font-size:13px">${t}</b></div><div class="row" style="gap:10px;margin-top:10px"><span class="b b-sm" style="width:30px;padding:0">−</span><span class="t1" style="font-size:28px;width:40px;text-align:center">${i ? 12 : 11}</span><span class="b b-sm" style="width:30px;padding:0">+</span></div></div>`).join('')}</div></div>
<div style="margin-top:16px">${sectionTitle('NAMES ON SCREEN · RIOT ID → DISPLAY')}${[['kairo#fnc1', 'KAIRO'], ['vexx#7781', 'VEX'], ['m1ra#gg', 'MIRA']].map(([r, d]) => `<div class="row" style="gap:10px;margin-top:6px"><span class="field mono" style="flex:1;font-size:12px;color:${C.secondary}">${r}</span>${icon('chevron', C.hint, 12)}<span class="field" style="flex:1">${d}</span></div>`).join('')}</div>
<div style="margin-top:16px">${sectionTitle('SIDES & SERIES')}<div class="row" style="gap:10px"><span class="b b-sm">Swap sides</span><span class="b b-sm">Series 1 – 1</span><span class="b b-sm">Observed: KAIRO</span></div></div>
<div style="margin-top:18px;padding:14px;background:rgba(251,191,36,.06);box-shadow:inset 0 0 0 1px rgba(251,191,36,.4)">
<b style="font-size:13.5px;color:#FDE68A">Also update the bracket?</b><p class="muted" style="font-size:12.5px;margin-top:4px">This changes a map score. Esportra can record it as a correction on the match, with you as the source.</p>
<div class="row" style="gap:8px;margin-top:10px"><span class="b b-sm">On air only</span><span class="b b-sm b-pri">Air and bracket</span></div></div>
<div style="margin-top:18px">${sectionTitle('HISTORY')}<div class="mono" style="font-size:11px;line-height:1.9;color:${C.secondary}">20:12:41 Ayesha · score 12–11 → 11–12<br>20:02:10 Ayesha · name vexx#7781 → VEX<br>19:58:03 Feed · roster loaded (10 players)</div></div>
<div class="row" style="gap:10px;position:absolute;left:24px;right:24px;bottom:22px"><span class="b">Undo last</span><span class="b b-pri" style="margin-left:auto">Apply · on air now</span></div></div>
<div style="position:absolute;left:40px;top:40px;width:560px">${monitor(img('ingame-full.jpg'), { w: 560, label: 'PGM · ON AIR' })}<p class="hint" style="font-size:12px;margin-top:10px">The console stays visible behind the drawer, so you see the fix land.</p></div>`;
  return wrap('hud/desk-13-data-fix', 'Data', body, `${ann(1, 1018, 196)}${ann(2, 1018, 300)}${ann(3, 1018, 420)}${ann(4, 1018, 610)}${ann(5, 1018, 760)}`);
}

export function offline() {
  const body = `<div style="position:absolute;inset:0;padding:22px 24px">
<div class="row" style="gap:12px;padding:12px 16px;background:${TONES.warning.bg};box-shadow:inset 0 0 0 1px ${TONES.warning.ring}">${icon('wifi', C.warning, 16)}<b style="font-size:14px;color:#FDE68A">Offline for 6 min · the show is running on this PC</b><span class="muted" style="font-size:12.5px">Graphics, autopilot and OBS keep going. Changes sync when the internet is back.</span><span class="mono hint" style="margin-left:auto;font-size:11.5px">retrying in 8 s</span></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px">
<div class="box" style="padding:16px">${sectionTitle('WAITING TO SYNC · 4', '<span class="b b-sm">Retry now</span>')}
${[['Map 2 result · C5 13–10', 'To the bracket', 'clock'], ['Score fix · 11–12', 'Correction record', 'clock'], ['9 holds and takes', 'Show report', 'clock'], ['Sponsor on-air minutes', 'Show report', 'clock']].map(([t, d]) => `<div class="row" style="gap:10px;padding:11px 0;border-bottom:1px solid rgba(255,255,255,.05)">${icon('clock', C.hint, 14)}<div><span style="font-size:13px">${t}</span><div class="hint" style="font-size:11.5px">${d}</div></div><span class="mono hint" style="margin-left:auto;font-size:11px">queued</span></div>`).join('')}
<p class="hint" style="font-size:12px;margin-top:12px">Kept on disk. Safe through a restart.</p></div>
<div class="box" style="padding:16px">${sectionTitle('WHAT STILL WORKS OFFLINE')}
${[['Every graphic and browser source', true], ['Autopilot and OBS switching', true], ['Game data from the observer PC (LAN)', true], ['New matches from the schedule', false], ['Team edits made on the website', false], ['Remote monitor and phone remote', false]].map(([t, ok]) => `<div class="row" style="gap:10px;padding:9px 0;font-size:13px">${ok ? icon('check', C.success, 14) : icon('x', C.hint, 14)}<span style="${ok ? '' : `color:${C.hint}`}">${t}</span></div>`).join('')}</div></div>
<div class="box" style="margin-top:18px;padding:16px;box-shadow:inset 0 0 0 1px ${TONES.critical.ring}">${sectionTitle('BACK ONLINE · ONE THING NEEDS YOU', chip('Conflict', 'critical'))}
<p class="muted" style="font-size:13px">While you were offline, an admin moved <b style="color:${C.ink}">Zero Ping vs Ghost Unit</b> to Booth B. This PC also queued it for 21:30.</p>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px">
<div style="padding:14px;background:rgba(255,255,255,.03);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)"><div class="cap" style="font-size:9px">ON THE WEBSITE</div><b style="display:block;font-size:14px;margin-top:6px">Booth B · 21:30</b><p class="hint" style="font-size:12px;margin-top:4px">Changed by Bilal at 20:21</p><span class="b b-sm b-pri" style="margin-top:10px">Use this</span></div>
<div style="padding:14px;background:rgba(255,255,255,.03);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)"><div class="cap" style="font-size:9px">ON THIS PC</div><b style="display:block;font-size:14px;margin-top:6px">Studio PC · 21:30</b><p class="hint" style="font-size:12px;margin-top:4px">Queued by autopilot at 20:16</p><span class="b b-sm" style="margin-top:10px">Keep mine</span></div></div></div>
<div class="box" style="margin-top:18px;padding:14px 16px">${sectionTitle('CONNECTION · LAST 2 HOURS')}
<div style="position:relative;height:22px;display:flex;gap:2px">${[[60, 's'], [3, 'w'], [25, 's'], [6, 'o']].map(([w, t]) => `<div style="flex:${w};background:${t === 's' ? 'rgba(52,211,153,.35)' : t === 'w' ? 'rgba(251,191,36,.45)' : 'rgba(251,191,36,.75)'}"></div>`).join('')}</div>
<div class="row" style="justify-content:space-between;margin-top:8px"><span class="mono hint" style="font-size:10.5px">18:30</span><span class="mono hint" style="font-size:10.5px">19:30 · 40 s dropout</span><span class="mono" style="font-size:10.5px;color:#FDE68A">offline since 20:15</span></div></div></div>`;
  return wrap('hud/desk-14-offline-sync', 'Sync', body, `${ann(1, 85, 93)}${ann(2, 85, 156)}${ann(3, 834, 156)}${ann(4, 85, 527)}${ann(5, 85, 788)}`, { offline: true });
}
