-- Payments & Payouts schema (idempotent, safe to re-run)

-- Ensure gen_random_uuid() is available
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Settings
CREATE TABLE IF NOT EXISTS finance_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_fee_percent NUMERIC(5,2) NOT NULL DEFAULT 10.00,
    min_payout_cents     BIGINT NOT NULL DEFAULT 1000,
    payout_hold_days     INTEGER NOT NULL DEFAULT 3,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure at least one row
INSERT INTO finance_settings (platform_fee_percent, min_payout_cents, payout_hold_days)
SELECT 10.00, 1000, 3
WHERE NOT EXISTS (SELECT 1 FROM finance_settings);

-- 2) Wallets
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'wallet_owner') THEN
    CREATE TYPE wallet_owner AS ENUM ('platform','organizer','team','user');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS wallets (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_type  wallet_owner NOT NULL,
    owner_id    UUID NOT NULL,
    balance_cents BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS wallets_owner_unique
ON wallets(owner_type, owner_id);

-- 3) Payments
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
    CREATE TYPE payment_status AS ENUM ('pending','succeeded','failed','refunded');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS payments (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    team_id            UUID,
    organizer_id       UUID,
    tournament_id      UUID,
    amount_cents       BIGINT NOT NULL,
    currency           TEXT NOT NULL DEFAULT 'usd',
    platform_fee_cents BIGINT NOT NULL DEFAULT 0,
    net_amount_cents   BIGINT NOT NULL DEFAULT 0,
    provider           TEXT NOT NULL DEFAULT 'stripe',
    provider_payment_id TEXT,
    status             payment_status NOT NULL DEFAULT 'pending',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_tournament ON payments(tournament_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

-- 4) Ledger (double-entry style per wallet)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ledger_type') THEN
    CREATE TYPE ledger_type AS ENUM ('credit','debit');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS ledger_entries (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_id    UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    entry_type   ledger_type NOT NULL,
    reference_type TEXT,
    reference_id   UUID,
    memo         TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ledger_wallet ON ledger_entries(wallet_id);

-- 5) Payout Requests
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_status') THEN
    CREATE TYPE payout_status AS ENUM ('requested','approved','rejected','paid','failed');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS payout_requests (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_id      UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    amount_cents   BIGINT NOT NULL,
    destination    TEXT,
    status         payout_status NOT NULL DEFAULT 'requested',
    approved_by    UUID REFERENCES auth.users(id),
    processed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6) Refunds
CREATE TABLE IF NOT EXISTS refunds (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_id    UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    amount_cents  BIGINT NOT NULL,
    reason        TEXT,
    status        TEXT NOT NULL DEFAULT 'pending',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7) Webhook Events (idempotency)
CREATE TABLE IF NOT EXISTS webhook_events (
    idempotency_key TEXT PRIMARY KEY,
    event_type      TEXT,
    payload         JSONB,
    processed       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS enable
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payout_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename='payments' AND policyname='admins see all payments'
  ) THEN
    CREATE POLICY "admins see all payments" ON payments
      FOR SELECT USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role='admin'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename='webhook_events' AND policyname='admins see webhooks'
  ) THEN
    CREATE POLICY "admins see webhooks" ON webhook_events
      FOR SELECT USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role='admin'));
  END IF;
END $$;

-- Minimal user visibility: users see their own payments
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename='payments' AND policyname='users see own payments'
  ) THEN
    CREATE POLICY "users see own payments" ON payments
      FOR SELECT USING (user_id = auth.uid());
  END IF;
END $$;

-- Wallet RPCs: credit/debit with non-negative checks
CREATE OR REPLACE FUNCTION ensure_wallet(p_owner wallet_owner, p_owner_id UUID)
RETURNS UUID AS $$
DECLARE w_id UUID; BEGIN
  SELECT id INTO w_id FROM wallets WHERE owner_type=p_owner AND owner_id=p_owner_id;
  IF w_id IS NULL THEN
    INSERT INTO wallets(owner_type, owner_id) VALUES (p_owner, p_owner_id) RETURNING id INTO w_id;
  END IF;
  RETURN w_id;
END; $$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION wallet_credit(p_wallet UUID, p_amount BIGINT, p_ref_type TEXT, p_ref_id UUID, p_memo TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  IF p_amount <= 0 THEN RAISE EXCEPTION 'amount must be > 0'; END IF;
  UPDATE wallets SET balance_cents = balance_cents + p_amount WHERE id=p_wallet;
  INSERT INTO ledger_entries(wallet_id, amount_cents, entry_type, reference_type, reference_id, memo)
  VALUES (p_wallet, p_amount, 'credit', p_ref_type, p_ref_id, p_memo);
  RETURN TRUE;
END; $$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION wallet_debit(p_wallet UUID, p_amount BIGINT, p_ref_type TEXT, p_ref_id UUID, p_memo TEXT)
RETURNS BOOLEAN AS $$
DECLARE bal BIGINT; BEGIN
  IF p_amount <= 0 THEN RAISE EXCEPTION 'amount must be > 0'; END IF;
  SELECT balance_cents INTO bal FROM wallets WHERE id=p_wallet;
  IF bal IS NULL THEN RAISE EXCEPTION 'wallet not found'; END IF;
  IF bal < p_amount THEN RAISE EXCEPTION 'insufficient funds'; END IF;
  UPDATE wallets SET balance_cents = balance_cents - p_amount WHERE id=p_wallet;
  INSERT INTO ledger_entries(wallet_id, amount_cents, entry_type, reference_type, reference_id, memo)
  VALUES (p_wallet, p_amount, 'debit', p_ref_type, p_ref_id, p_memo);
  RETURN TRUE;
END; $$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT SELECT ON finance_settings, payments, wallets, ledger_entries, payout_requests, refunds, webhook_events TO authenticated;
GRANT EXECUTE ON FUNCTION ensure_wallet, wallet_credit, wallet_debit TO authenticated;


