// Builds the Esportra design dataset.
//   npm i --no-save playwright   (once; uses the Chromium Playwright manages)
//   node design/source/build.mjs [filter]
// Writes editable HTML sources to design/source/html/, renders PNGs (and SVGs where an asset has one)
// into design/, and regenerates design/manifest.json.
import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { ROOT, hasLogo } from './lib.mjs';

const groups = ['identity', 'textures', 'directions', 'templates', 'ui'];
const assets = [];
for (const g of groups) {
  const file = path.join(ROOT, 'source', 'assets', `${g}.mjs`);
  if (existsSync(file)) assets.push(...(await import(file)).default.map((a) => ({ group: g, ...a })));
}

const filter = process.argv[2];
const todo = filter ? assets.filter((a) => a.id.includes(filter)) : assets;

const launch = { executablePath: process.env.CHROMIUM_PATH || (existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined) };
const browser = await chromium.launch(launch);
const ctx = await browser.newContext({ deviceScaleFactor: 1 });

for (const a of todo) {
  const html = a.html();
  const htmlPath = path.join(ROOT, 'source', 'html', `${a.id}.html`);
  mkdirSync(path.dirname(htmlPath), { recursive: true });
  // HTML sources sit two levels below design/source/html/<group>/, so fonts resolve at ../../fonts
  const depth = a.id.split('/').length - 1;
  const up = '../'.repeat(depth);
  writeFileSync(htmlPath, html.replaceAll("url('../fonts/", `url('${up}../fonts/`).replaceAll('src="../../identity/', `src="${up}../../identity/`));
  if (a.svg) {
    const svgPath = path.join(ROOT, a.out.replace(/\.png$/, '.svg'));
    mkdirSync(path.dirname(svgPath), { recursive: true });
    writeFileSync(svgPath, a.svg());
  }
  const page = await ctx.newPage();
  await page.setViewportSize({ width: a.w, height: a.h });
  await page.goto('file://' + htmlPath);
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(80);
  const out = path.join(ROOT, a.out);
  mkdirSync(path.dirname(out), { recursive: true });
  await page.screenshot({ path: out, omitBackground: !!a.transparent });
  await page.close();
  console.log('✓', a.out);
}
await browser.close();

const manifest = {
  name: 'Esportra design dataset',
  generated: new Date().toISOString().slice(0, 10),
  source: 'design/source/build.mjs',
  canonical: ['.claude/skills/esportra-brand/', '.claude/skills/design-recipe/', 'DESIGN.md'],
  logo: hasLogo() ? 'identity/logo/esportra-logo-white.png' : 'missing - export the mark from Supabase storage into design/identity/logo/ and rebuild',
  sampleData: 'Team names, players, crests, amounts and dates are fictional samples for layout reference. Never publish them as real.',
  assets: assets.map((a) => {
    const file = path.join(ROOT, a.out);
    return {
      id: a.id,
      group: a.group,
      file: a.out,
      svg: a.svg ? a.out.replace(/\.png$/, '.svg') : undefined,
      source: `source/html/${a.id}.html`,
      size: [a.w, a.h],
      transparent: !!a.transparent || undefined,
      direction: a.direction,
      use: a.use,
      description: a.description,
      tags: a.tags,
      bytes: existsSync(file) ? statSync(file).size : undefined,
    };
  }),
};
writeFileSync(path.join(ROOT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`manifest: ${manifest.assets.length} assets`);

// Human index with previews (regenerated with the manifest)
const titles = { identity: 'Identity', textures: 'Textures and backgrounds', directions: 'Design directions', templates: 'Templates', ui: 'UI reference' };
const intro = {
  identity: 'The invariants: colour, contrast, type, signature moves, motion, space and shape, logo usage.',
  textures: 'Regenerable backgrounds and overlays. Each has an SVG next to the PNG, so it scales to any size.',
  directions: "One board per direction from `design-recipe`: a composed example plus when to use it, ingredients and do/don't. Choose the direction from the context signals first, then look here.",
  templates: 'Production-shaped layouts for social, web, email, stream and venue screens, filled with fictional sample data.',
  ui: 'States every product flow must design, drawn with the real kit tokens.',
};
const lines = ['# Esportra design dataset: index', '', '<!-- Generated by design/source/build.mjs. Do not edit by hand. -->', '', `${manifest.assets.length} assets. Logo: ${hasLogo() ? 'real mark composited' : 'slots shown (see identity/logo/README.md)'}. Sample names, crests, amounts and dates are fictional.`, ''];
for (const g of groups) {
  const list = manifest.assets.filter((a) => a.group === g);
  if (!list.length) continue;
  lines.push(`## ${titles[g]}`, '', intro[g], '', '| Preview | Asset | Size | Direction | What it shows | Use |', '|---|---|---|---|---|---|');
  for (const a of list) {
    const links = [`[\`${a.file}\`](${a.file})`, a.svg ? `[svg](${a.svg})` : null, `[html source](${a.source})`].filter(Boolean).join('<br>');
    lines.push(`| <img src="${a.file}" width="220"> | ${links} | ${a.size[0]}×${a.size[1]}${a.transparent ? ' transparent' : ''} | ${a.direction || '-'} | ${a.description} | ${a.use || '-'} |`);
  }
  lines.push('');
}
writeFileSync(path.join(ROOT, 'INDEX.md'), lines.join('\n'));
console.log('index: INDEX.md');
