// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggmoxgiddhhvimbdolsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbW94Z2lkZGhodmltYmRvbHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjMwMjksImV4cCI6MjA2MTIzOTAyOX0.yqJtUwPNueSYOrB4Mi2ClVcCaDSyzT3G_RSYt9U2F7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);