// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://abbjywqlxnxoutllbgke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYmp5d3FseG54b3V0bGxiZ2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTM0NzQsImV4cCI6MjA3NTY2OTQ3NH0.k6aKFMT1Q-oou4FrKb8kcRWFxP-Y_TgyEobZ5GHy430";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);